server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doggo-db
    username: postgres
    password: 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: true

doggo:
  security:
    token:
      secret: "Tu5AU1hAoC1hHH3T4NoLx/JPKmwKW/QbkMbiz4oMnCsXSTWCGbwlVa2X00dlupiprQwgD59/Mk8cd7molW/W3hS2t/LdiFpNA0tMM1INXKvNOhHnCM5zZn3heHWxSrcM0hdEgbmQNHJUBB+US5wL5RTGGcY0JhijH+K1ANpLm+zChQrbEbneVDEpNG2YW8pKwFD4IvYyhTKOZbHCrEBHAmmflv5UDATb2Q3niA=="
      expiration-time-in-seconds: 86400