server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doggo-db
    username: postgres
    password: 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: true

doggo:
  security:
    token:
      secret: "g4OKWjQeWlcnERgrbJtCxSAmv7eJZrjjb/rBYBOTHKzCTO4FJnzneXQQ1J8XZGUJvoRMyNV+54PdqPztqFbJ4Q=="