version: "2.1"

services:
  database:
    container_name: doggo-db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: doggo-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1